# # # select and Ctrl + / ka use kark comment in the python

# # print("Hello Amir Khan")
# # print("Itam Love Amir")

# # A=10
# # B=20
# # K=200
# # C=A *B
# # K=A *K

# # print("The value of C is:",C)2
# # print("The value of K is:",K)

# # print(A+B)
# # print(C+K)

# # #N=input("Enter your name:")
# # #print("Hello",N)


# # EnterName=input("Enter your name:")
# # print("Hello Mr",EnterName)
# # Age programimg for thr Vote

# # age=17
# # if(age>=18):
# #     print("You are eligible for vote")

# # # else:
# # #     print("You are not eligible for vote")



# # #     age = int(input("Enter your age:"))

# # # if age >= 18:
# # #     print("You are eligible for vote")
# # # else:
# # #     print("You are not eligible for vote")

# # # ############ Multiple conditions in python

# # Marks = int(input("Enter your marks:"))

# # if Marks >= 80:
# #     print("You got A+ grade")
# # elif Marks >= 70:
# #     print("You got A grade")
# # elif Marks >= 60:
# #     print("You got B grade")
# # else:
# #     print("You failed")

#  ######################################   ##########################  range(start, stop, step)

# for i in range(10):
#     print(i)

# for i in range(10):

#     if i == 5:
#         break

#     print(i)
# #############################################

# # password = "python123"

# # while True:
# #     user = input("Enter Password: ")

# #     if user == password:
# #         print("Login Successful")
# #         break

# #     print("Wrong Password")

# ############################################
    # Password = "Amir@123"
    # while True:
    #     user = input("Enter Password: ")
    #     if user == Password:
    #         print("Login Successful 🥷🥷🥷🥷")
    #         break
    #     print("Wrong Password ")

#         #######################################

# # text = "Python Programming"

# # print(text.upper())
# # print(text.lower())
# # print(text.replace("Python","Java"))
# # print(text.split())
# # print(len(text))
# ###################################

# def greet():
#     print("Hello")

# greet()
######################

# def add(a, b):
#     print(a + b)

# def sub(a, b):
#     print(a - b)

# add(10, 20)
# add(5, 7)
# sub(10, 20)
# sub(5, 7)


#  Password = "Amir@123"
#     while True:
#         user = input("Enter Password: ")
#         if user == Password:
#             print("Login Successfull")
#             break
#         print("Wrong Password ")




name=int(input("Enter your name: "))

if name %2 ==0:
    print("Your name is even.")

else:

    print("your number is odd")
